`ifndef NUM_PE
    `define NUM_PE 2
`endif
module sparse_array #(
    parameter DATA_WIDTH = 8,
    parameter OUT_WIDTH  = 32,
    parameter NUM_PE     = `NUM_PE,
    parameter NUM_GROUPS = 8
)(
    input  logic clk,
    input  logic rst,
    input  logic start,

    // Two non-zero values for every 2:4 sparse group
    input logic signed [DATA_WIDTH-1:0] value0 [NUM_GROUPS],
    input logic signed [DATA_WIDTH-1:0] value1 [NUM_GROUPS],

    // Indices of the two non-zero values
    input logic [1:0] index0 [NUM_GROUPS],
    input logic [1:0] index1 [NUM_GROUPS],

    // Dense input vector
    input logic signed [DATA_WIDTH-1:0] b0 [NUM_GROUPS],
    input logic signed [DATA_WIDTH-1:0] b1 [NUM_GROUPS],
    input logic signed [DATA_WIDTH-1:0] b2 [NUM_GROUPS],
    input logic signed [DATA_WIDTH-1:0] b3 [NUM_GROUPS],

    output logic signed [OUT_WIDTH-1:0] result,
    output logic done
);

    integer i;
    integer pe;

    // Partial result generated by each PE
    logic signed [OUT_WIDTH-1:0] pe_result [NUM_PE];

    // Final result after combining all PEs
    logic signed [OUT_WIDTH-1:0] total_result;

    // Selected dense values corresponding to sparse indices
    logic signed [DATA_WIDTH-1:0] selected_value0;
    logic signed [DATA_WIDTH-1:0] selected_value1;


    // ------------------------------------------------
    // Sparse computation
    // ------------------------------------------------

    always_comb begin

        // Clear PE results
        for (pe = 0; pe < NUM_PE; pe = pe + 1)
            pe_result[pe] = '0;

        selected_value0 = '0;
        selected_value1 = '0;


        // Process every sparse group
        for (i = 0; i < NUM_GROUPS; i = i + 1) begin

            // ----------------------------------------
            // Select B corresponding to index0
            // ----------------------------------------

            case (index0[i])
                2'd0: selected_value0 = b0[i];
                2'd1: selected_value0 = b1[i];
                2'd2: selected_value0 = b2[i];
                2'd3: selected_value0 = b3[i];
                default: selected_value0 = '0;
            endcase


            // ----------------------------------------
            // Select B corresponding to index1
            // ----------------------------------------

            case (index1[i])
                2'd0: selected_value1 = b0[i];
                2'd1: selected_value1 = b1[i];
                2'd2: selected_value1 = b2[i];
                2'd3: selected_value1 = b3[i];
                default: selected_value1 = '0;
            endcase


            // ----------------------------------------
            // Round-robin mapping
            //
            // NUM_PE = 2:
            //   Group 0 -> PE 0
            //   Group 1 -> PE 1
            //   Group 2 -> PE 0
            //   Group 3 -> PE 1
            //   ...
            // ----------------------------------------

            pe = i % NUM_PE;


            // ----------------------------------------
            // Sparse MAC computation
            // ----------------------------------------

            pe_result[pe] =
                pe_result[pe]
                + ($signed(value0[i]) * $signed(selected_value0))
                + ($signed(value1[i]) * $signed(selected_value1));

        end


        // --------------------------------------------
        // Combine all PE partial results
        // --------------------------------------------

        total_result = '0;

        for (pe = 0; pe < NUM_PE; pe = pe + 1)
            total_result = total_result + pe_result[pe];

    end


    // ------------------------------------------------
    // Output register
    // ------------------------------------------------

    always_ff @(posedge clk) begin

        if (rst) begin

            result <= '0;
            done   <= 1'b0;

        end

        else begin

            done <= 1'b0;

            if (start) begin

                result <= total_result;
                done   <= 1'b1;

            end

        end

    end

endmodule