#!/usr/bin/env python3
"""Regenerate results/summary/ from the published run records.

    python scripts/summarize_runs.py                 # results/ -> results/summary/

Everything in the README's results tables comes from here, and this reads
nothing but the iteration records in results/<run>/iter_*.json.

Energy is reported twice. `energy_recorded_uJ` is what the loop scored at the
time. `energy_uJ` re-scores the same measured counters with the CURRENT
t1_model, so both runs are compared under one model:

  * V1's records were scored with an earlier model (256 KB SRAM floor, no T-B
    credit), and
  * V2's records credited sub-row T-B granules the hardware cannot skip
    (fixed in zbu_model; see docs/results.md).

Cycles, off-chip bytes, area and equivalence are measurements and are never
re-scored.
"""
from __future__ import annotations

import csv
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

import t1_model as T                                     # noqa: E402
from design_state import DesignState                     # noqa: E402
from metrics import Metrics                              # noqa: E402

RUNS = [("v2-final15", "V2 (final loop)"), ("v1-final15", "V1 (first loop)")]
FIELDS = ["iteration", "verdict", "layer", "change", "cycles", "offchip_bytes",
          "area_mm2", "energy_uJ", "energy_recorded_uJ", "perf_per_watt_gops_w",
          "equiv_mismatches", "repair", "prediction", "wall_min"]


def rows_for(run: str) -> list:
    wl = None
    out = []
    for f in sorted(glob.glob(os.path.join(ROOT, "results", run, "iter_*.json"))):
        d = json.load(open(f))
        s = DesignState.from_dict(d["state"]) if d.get("state") else None
        if wl is None and s is not None:
            wl = T.Workload.from_stats(json.load(open(os.path.join(
                ROOT, "workload", "generated", f"spmm_{s.workload}.json"))), dense_mode=s.dense_mode)
        mv = d.get("move") or {}
        # move.changed is {field: [child_value, parent_value]}
        change = "; ".join(f"{k} {v[1]}->{v[0]}" for k, v in (mv.get("changed") or {}).items())
        r = {"iteration": d["iteration"], "verdict": d.get("verdict"),
             "layer": mv.get("class", ""), "change": change or ("baseline" if d["iteration"] == 1 else ""),
             "equiv_mismatches": d.get("equiv_mismatches", ""),
             "wall_min": round((d.get("wall_clock_s") or 0) / 60, 1)}
        rp = d.get("repair") or {}
        if rp:
            r["repair"] = f"{rp.get('first_verdict')} -> {rp.get('outcome')} ({len(rp.get('attempts') or [])})"
        ps = d.get("prediction_score") or {}
        if ps.get("scored"):
            r["prediction"] = f"{ps['hits']}/{ps['scored']}"
        if "admit_info" in d:
            mm = d["metrics"]
            m = Metrics(mm["cycles"], mm["macs_useful"], mm["counters"])
            er = T.energy_report(s, m, wl, d["period_ns"])
            r.update(cycles=m.cycles, offchip_bytes=m.bytes_offchip(),
                     area_mm2=round(d["area_um2"] / 1e6, 4),
                     energy_uJ=round(er.energy_pj / 1e6, 2),
                     energy_recorded_uJ=round(d["energy_pj"] / 1e6, 2),
                     perf_per_watt_gops_w=round(er.perf_per_watt_gops_w, 2),
                     _t=m.cycles * d["period_ns"], _A=d["area_um2"], _E=er.energy_pj)
        out.append(r)
    return out


def front(rows: list) -> list:
    pts = [r for r in rows if "_t" in r and str(r["verdict"]).startswith("ADMIT")]

    def dom(a, b):
        return (a["_t"] <= b["_t"] and a["_A"] <= b["_A"] and a["_E"] <= b["_E"]
                and (a["_t"] < b["_t"] or a["_A"] < b["_A"] or a["_E"] < b["_E"]))
    return [r for r in pts if not any(dom(o, r) for o in pts)]


def main() -> int:
    outdir = os.path.join(ROOT, "results", "summary")
    os.makedirs(outdir, exist_ok=True)
    md = ["# Run summary (generated by scripts/summarize_runs.py)", "",
          "Energy is modelled and re-scored with the current `t1_model` for both runs; "
          "cycles, off-chip bytes and area are measured. Baseline = stock Gemmini running "
          "the block-sparse SpMM kernel on `dnn512`.", ""]
    for run, label in RUNS:
        rows = rows_for(run)
        with open(os.path.join(outdir, f"{run}.csv"), "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=FIELDS, extrasaction="ignore")
            w.writeheader()
            w.writerows(rows)
        base = rows[0]
        md += [f"## {label}: `{run}`", "",
               "| it | verdict | layer | change | cycles | area mm² | energy µJ |",
               "|---|---|---|---|---|---|---|"]
        for r in rows:
            md.append(f"| {r['iteration']} | {r['verdict']} | {r['layer']} | {r['change']} | "
                      f"{r.get('cycles', '') and format(r['cycles'], ',')} | {r.get('area_mm2', '')} | "
                      f"{r.get('energy_uJ', '')} |")
        md += ["", "Pareto front:", ""]
        for r in front(rows):
            md.append(f"- iteration {r['iteration']}: {base['cycles'] / r['cycles']:.2f}x cycles, "
                      f"{100 * (1 - r['_A'] / base['_A']):.1f}% smaller, "
                      f"{base['_E'] / r['_E']:.2f}x less energy, "
                      f"{base['offchip_bytes'] / r['offchip_bytes']:.1f}x less off-chip traffic")
        md.append("")
    open(os.path.join(outdir, "README.md"), "w").write("\n".join(md) + "\n")
    print("\n".join(md))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
